# Generated by Django 4.2.3 on 2023-07-27 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publish_data',
        ),
        migrations.AddField(
            model_name='books',
            name='publish_year',
            field=models.PositiveIntegerField(default=1800, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
