# Generated by Django 4.2.3 on 2023-07-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_remove_books_publish_data_books_publish_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='first_name',
            new_name='First name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='last_name',
            new_name='Last name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publish_year',
            new_name='year',
        ),
    ]
